#!/bin/sh
# A17 build compatibility patches (applied after each sync)
[ "$1" != "sync" ] && exit 0

PDIR=".repo/local_manifests/patches"

apply() {
    local file="$1" repo="$2"
    if patch --dry-run -d "$repo" -Np1 -s < "$file" 2>/dev/null; then
        patch -d "$repo" -Np1 -s < "$file"
        echo "[repo-hook] Patched $repo"
    fi
}

apply "$PDIR/0001-skcms-vendor_available.patch" external/skia
apply "$PDIR/0002-hwy-vendor_available.patch"   external/google-highway
apply "$PDIR/0003-xmp-vendor_available.patch"   external/XMP-Toolkit-SDK
apply "$PDIR/0004-zuid_md5-vendor_available.patch" external/XMP-Toolkit-SDK
apply "$PDIR/0005-qcom-display-mutex-include.patch"  vendor/qcom/opensource/display
apply "$PDIR/0006-recovery-algorithm-include.patch" bootable/recovery
apply "$PDIR/0007-launcher3-sdk-version.patch"    packages/apps/Launcher3
apply "$PDIR/0008-vold-algorithm-include.patch"    system/vold
apply "$PDIR/0009-battery-listener-mutex.patch"    hardware/qcom-caf/sm8350/audio
apply "$PDIR/0010-volume-manager-vector.patch"     bootable/recovery
apply "$PDIR/0011-ipacm-vector.patch"              vendor/qcom/opensource/data-ipa-cfg-mgr-legacy-um
apply "$PDIR/0012-sound-trigger-extern.patch"      vendor/qcom/opensource/audio-hal
apply "$PDIR/0013-sound-trigger-definition.patch"  vendor/qcom/opensource/audio-hal
